[package]
name = "wlexpcli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12.8", features = ["json", "stream"] }
serde_json = "1.0"
indicatif = "0.17.8"
zip = "2.2.0"
tempfile = "3.2"
futures-util = "0.3"
